<?php
/**
 * Shared entity data.
 *
 * Services, team members, and other repeatable data that appears
 * across multiple pages and sections. Define once here, reference
 * everywhere via anchor_get_data('services') etc.
 *
 * @package Anchor_Starter_Child
 * @since   1.0.0
 */

return [

	// ── Services ────────────────────────────────────────────────────
	'services' => [
		[
			'id'          => 'service-one',
			'title'       => 'Service One',
			'subtitle'    => 'Service One',
			'icon'        => 'heart',
			'url'         => '/services/service-one/',
			'text'        => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
			'description' => 'Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Maecenas faucibus mollis interdum.',
			'image'       => 'service_tab_1',
			'items'       => ['Donec ullamcorper nulla non metus', 'Vestibulum id ligula porta felis', 'Maecenas sed diam eget risus varius', 'Integer posuere erat a ante venenatis'],
		],
		[
			'id'          => 'service-two',
			'title'       => 'Service Two',
			'subtitle'    => 'Service Two',
			'icon'        => 'users',
			'url'         => '/services/service-two/',
			'text'        => 'Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui maecenas faucibus mollis interdum.',
			'description' => 'Maecenas sed diam eget risus varius blandit sit amet non magna. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.',
			'image'       => 'service_tab_2',
			'items'       => ['Cras mattis consectetur purus', 'Nullam quis risus eget urna', 'Morbi leo risus porta ac consectetur', 'Aenean lacinia bibendum nulla'],
		],
		[
			'id'          => 'service-three',
			'title'       => 'Service Three',
			'subtitle'    => 'Service Three',
			'icon'        => 'compass',
			'url'         => '/services/service-three/',
			'text'        => 'Maecenas sed diam eget risus varius blandit sit amet non magna. Integer posuere erat a ante venenatis dapibus.',
			'description' => 'Cras mattis consectetur purus sit amet fermentum. Nullam quis risus eget urna mollis ornare vel eu leo. Morbi leo risus, porta ac.',
			'image'       => 'service_tab_3',
			'items'       => ['Vivamus sagittis lacus vel augue', 'Eget dolor aenean faucibus nibh', 'Cum sociis natoque penatibus', 'Nascetur ridiculus mus donec'],
		],
		[
			'id'          => 'service-four',
			'title'       => 'Service Four',
			'subtitle'    => 'Service Four',
			'icon'        => 'shield',
			'url'         => '/services/service-four/',
			'text'        => 'Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper at eget metus.',
			'description' => 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sed odio dui. Cras justo odio.',
			'image'       => 'service_tab_4',
			'items'       => ['Dapibus ac facilisis in egestas', 'Morbi leo risus porta ac', 'Curabitur blandit tempus porttitor', 'Praesent commodo cursus magna'],
		],
		[
			'id'          => 'service-five',
			'title'       => 'Service Five',
			'subtitle'    => 'Service Five',
			'icon'        => 'search',
			'url'         => '/services/service-five/',
			'text'        => 'Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras mattis consectetur purus sit amet fermentum.',
			'description' => 'Vestibulum id ligula porta felis euismod semper. Nullam id dolor id nibh ultricies vehicula ut id elit. Maecenas faucibus mollis.',
			'image'       => 'service_tab_5',
			'items'       => ['Nullam id dolor id nibh ultricies', 'Vehicula ut id elit vestibulum', 'Fusce dapibus tellus ac cursus', 'Commodo tortor mauris condimentum'],
		],
	],

	// ── Team Members ────────────────────────────────────────────────
	'team' => [
		[
			'name'  => 'Team Member One',
			'role'  => 'Founder & Executive Director',
			'photo' => 'team_member_1',
			'url'   => '/about/#member-one',
			'slug'  => 'member-one',
			'bio'   => [
				'Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Maecenas faucibus mollis interdum. Nullam quis risus eget urna mollis ornare vel eu leo.',
				'Maecenas sed diam eget risus varius blandit sit amet non magna. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras mattis consectetur purus sit amet fermentum.',
			],
			'quote' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec sed odio dui.',
		],
		[
			'name'  => 'Team Member Two',
			'role'  => 'Director of Operations',
			'photo' => 'team_member_2',
			'url'   => '/about/#member-two',
			'slug'  => 'member-two',
			'bio'   => [
				'Cras justo odio, dapibus ut facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Aenean lacinia bibendum nulla sed consectetur.',
				'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.',
			],
			'quote' => 'Nullam quis risus eget urna mollis ornare vel eu leo. Cras mattis consectetur purus sit amet fermentum.',
		],
		[
			'name'  => 'Team Member Three',
			'role'  => 'Director of Programs',
			'photo' => 'team_member_3',
			'url'   => '/about/#member-three',
			'slug'  => 'member-three',
			'bio'   => [
				'Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.',
				'Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
			],
			'quote' => 'Maecenas sed diam eget risus varius blandit sit amet non magna. Vestibulum id ligula porta felis euismod semper.',
		],
		[
			'name'  => 'Team Member Four',
			'role'  => 'Community Outreach Lead',
			'photo' => 'team_member_4',
			'url'   => '/about/#member-four',
			'slug'  => 'member-four',
			'bio'   => [
				'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula.',
				'Etiam porta sem malesuada magna mollis euismod. Cras mattis consectetur purus sit amet fermentum. Donec ullamcorper nulla non metus auctor fringilla.',
			],
		],

	],

	// ── Products ────────────────────────────────────────────────────
	// Seeded on first load into the `laser_product` CPT at /shop/{slug}/.
	// 3 systems (featured=true) + 28 DEKA shop accessories. Accessory images
	// hotlinked from dekadentallasers.com for this demo build.
	'products' => [

		/* ─── 1. Systems (flagship instruments) ──────────────────── */
		[
			'slug'          => 'us-20d',
			'name'          => 'US-20D',
			'subtitle'      => 'CO₂ · 10,600 nm',
			'category'      => 'System',
			'category_slug' => 'system',
			'compatibility' => [],
			'price'         => 'Request quote',
			'price_note'    => 'Quoted per practice · trade-in programmes available',
			'image'         => 'product_us20d',
			'image_alt'     => 'DEKA US-20D CO₂ dental laser',
			'sku'           => 'DEKA-US20D',
			'tagline'       => 'A CO₂ workhorse, refined to the millimetre.',
			'description'   => "Compact enough to move between operatories, serious enough to carry the surgical day. The US-20D is the DEKA most dental practices meet first — and keep for life. An articulated arm, a mobile chassis, and the cleanest soft-tissue incision in the operatory.",
			'specs'         => [
				[ 'k' => 'Wavelength', 'v' => '10,600', 'sup' => 'nm' ],
				[ 'k' => 'Max power',  'v' => '20',     'sup' => 'W' ],
				[ 'k' => 'Delivery',   'v' => '7-joint articulated arm' ],
				[ 'k' => 'Modes',      'v' => 'CW · Pulsed · Super-Pulsed' ],
				[ 'k' => 'Chassis',    'v' => 'Mobile · Compact' ],
				[ 'k' => 'Warranty',   'v' => '2 years, full' ],
			],
			'includes'      => [],
			'featured'      => true,
		],
		[
			'slug'          => 'smartxide-ultraspeed2',
			'name'          => 'SmartXide Ultraspeed 2',
			'subtitle'      => 'CO₂ · PSD™ · 10,600 nm',
			'category'      => 'System',
			'category_slug' => 'system',
			'compatibility' => [],
			'price'         => 'Request quote',
			'price_note'    => 'Flagship platform · clinical dossier on request',
			'image'         => 'product_smartxide',
			'image_alt'     => 'DEKA SmartXide Ultraspeed 2 CO₂ dental laser',
			'sku'           => 'DEKA-SX2',
			'tagline'       => "Pulse Shape Design. A CO₂ you can't feel arrive.",
			'description'   => "Our proprietary PSD™ CO₂ platform. Energy shaped to the tissue, not the tissue shaped to the beam — with thermal confinement so disciplined the procedure ends before the patient notices it began. The industry's only CO₂ laser with four selectable pulse shapes.",
			'specs'         => [
				[ 'k' => 'Wavelength',   'v' => '10,600', 'sup' => 'nm' ],
				[ 'k' => 'Max power',    'v' => '30',     'sup' => 'W' ],
				[ 'k' => 'Signature',    'v' => 'PSD™ · SmartPulse™' ],
				[ 'k' => 'Pulse shapes', 'v' => 'Four · selectable' ],
				[ 'k' => 'Handpieces',   'v' => 'Surgical · QuietNite · Aesthetics' ],
				[ 'k' => 'Warranty',     'v' => '2 years, full' ],
			],
			'includes'      => [],
			'featured'      => true,
		],
		[
			'slug'          => 'smartperio',
			'name'          => 'SmartPerio',
			'subtitle'      => 'Nd:YAG · 1064 nm',
			'category'      => 'System',
			'category_slug' => 'system',
			'compatibility' => [],
			'price'         => 'Request quote',
			'price_note'    => 'Portable unit · perio & endo specialty',
			'image'         => 'product_smartperio',
			'image_alt'     => 'DEKA SmartPerio Nd:YAG laser',
			'sku'           => 'DEKA-SPERIO',
			'tagline'       => 'The periodontal standard, portable.',
			'description'   => "A pulsed Nd:YAG instrument built for the pocket, the furcation, and the quiet decisions that define a periodontal practice. Sterilises depth without surrendering the soft tissue above. Self-contained — no water or air connections required.",
			'specs'         => [
				[ 'k' => 'Wavelength',  'v' => '1064', 'sup' => 'nm' ],
				[ 'k' => 'Peak power',  'v' => '7',    'sup' => 'W' ],
				[ 'k' => 'Average',     'v' => '10',   'sup' => 'W' ],
				[ 'k' => 'Frequency',   'v' => 'up to 100', 'sup' => 'Hz' ],
				[ 'k' => 'Pulse',       'v' => 'Free-running · Pulsed · Biostim' ],
				[ 'k' => 'Delivery',    'v' => 'Fiber · 300 µm' ],
				[ 'k' => 'Form',        'v' => 'Self-contained · Portable' ],
				[ 'k' => 'Warranty',    'v' => '2 years, full' ],
			],
			'includes'      => [],
			'featured'      => true,
		],

		/* ─── 2. Nd:YAG accessories ─────────────────────────────── */
		[
			'slug'          => '300um-ndyag-fiber',
			'name'          => '300µm Nd:YAG Fiber',
			'subtitle'      => 'Delivery fiber',
			'category'      => 'Fiber',
			'category_slug' => 'fiber',
			'compatibility' => [ 'smartperio' ],
			'price'         => '$395.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/Fiber1-300x300.jpg',
			'image_alt'     => '300µm Nd:YAG delivery fiber',
			'tagline'       => 'Precision delivery for the SmartPerio.',
			'description'   => "Replacement 300-micron Nd:YAG delivery fiber for the SmartPerio platform. Each fiber is matched and tested against system tolerances before dispatch.",
			'specs'         => [
				[ 'k' => 'Core',       'v' => '300', 'sup' => 'µm' ],
				[ 'k' => 'Type',       'v' => 'Nd:YAG delivery fiber' ],
				[ 'k' => 'Compatible', 'v' => 'SmartPerio' ],
			],
			'featured'      => false,
		],
		[
			'slug'          => '300um-ndyag-fiber-qty-3',
			'name'          => '300µm Nd:YAG Fiber · Pack of 3',
			'subtitle'      => 'Delivery fibers',
			'category'      => 'Fiber',
			'category_slug' => 'fiber',
			'compatibility' => [ 'smartperio' ],
			'price'         => '$795.00',
			'price_note'    => 'Three-pack · stocking discount',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/Fiber3-300x300.jpg',
			'image_alt'     => '300µm Nd:YAG delivery fiber, pack of three',
			'tagline'       => "A quarter's stock of clean deliveries.",
			'description'   => "Three 300-micron Nd:YAG fibers bundled for practices that run a steady perio calendar. Keeps a spare on the shelf and a spare in the autoclave without reordering.",
			'specs'         => [
				[ 'k' => 'Quantity',   'v' => '3' ],
				[ 'k' => 'Core',       'v' => '300', 'sup' => 'µm' ],
				[ 'k' => 'Compatible', 'v' => 'SmartPerio' ],
			],
			'featured'      => false,
		],
		[
			'slug'          => 'hilt-biostimulation-handpiece-for-ndyag',
			'name'          => 'HILT Biostimulation Handpiece',
			'subtitle'      => 'Nd:YAG · Biostim',
			'category'      => 'Handpiece',
			'category_slug' => 'handpiece',
			'compatibility' => [ 'smartperio' ],
			'price'         => '$2,700.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/HILT-300x300.jpg',
			'image_alt'     => 'HILT biostimulation handpiece for Nd:YAG',
			'tagline'       => 'Biostimulation, in the hand.',
			'description'   => "A purpose-built handpiece that unlocks the SmartPerio's biostimulation mode for therapeutic applications — TMJ relief, post-operative recovery, and tissue regeneration protocols.",
			'specs'         => [
				[ 'k' => 'Modality',   'v' => 'HILT biostimulation' ],
				[ 'k' => 'Compatible', 'v' => 'SmartPerio · Nd:YAG' ],
			],
			'featured'      => false,
		],

		/* ─── 3. CO₂ handpieces ─────────────────────────────────── */
		[
			'slug'          => '4-standard-handpiece',
			'name'          => '4″ Standard Handpiece',
			'subtitle'      => 'CO₂ handpiece · bundle',
			'category'      => 'Handpiece',
			'category_slug' => 'handpiece',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$2,295.00',
			'price_note'    => 'Bundle · handpiece + attachments + tips',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA_SHP_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 4 inch standard handpiece',
			'sku'           => 'N81501',
			'tagline'       => 'The long reach, fully outfitted.',
			'description'   => "The 4-inch standard handpiece, supplied with the three attachments and tip library most CO₂ practices use daily. Designed for posterior reach and soft-tissue surgery.",
			'specs'         => [
				[ 'k' => 'Length',     'v' => '4″' ],
				[ 'k' => 'Compatible', 'v' => 'DEKA CO₂ systems' ],
				[ 'k' => 'SKU',        'v' => 'N81501' ],
			],
			'includes'      => [
				'Standard handpiece',
				'4″ mirror attachment',
				'4″ straight attachment',
				'4″ contra-angle attachment',
				'5 threaded straight tips',
				'5 threaded tapered perio tips',
			],
			'featured'      => false,
		],
		[
			'slug'          => '2-surgical-handpiece',
			'name'          => '2″ Surgical Handpiece',
			'subtitle'      => 'CO₂ handpiece · surgical',
			'category'      => 'Handpiece',
			'category_slug' => 'handpiece',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$2,295.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA_HP_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 2 inch surgical handpiece',
			'tagline'       => 'Close control, surgical intent.',
			'description'   => "The 2-inch handpiece for anterior work and tight access — paired with the surgical attachment set. A short, stiff instrument built around the clinician's hand.",
			'specs'         => [
				[ 'k' => 'Length',     'v' => '2″' ],
				[ 'k' => 'Compatible', 'v' => 'DEKA CO₂ systems' ],
			],
			'featured'      => false,
		],
		[
			'slug'          => 'handpiece-package-2-and-4',
			'name'          => 'Handpiece Package · 2″ + 4″',
			'subtitle'      => 'Complete CO₂ handpiece set',
			'category'      => 'Handpiece',
			'category_slug' => 'handpiece',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$3,995.00',
			'price_note'    => 'Saves $595 vs. separate purchase',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-Handpiece_Both_500x500-300x300.jpg',
			'image_alt'     => 'DEKA handpiece package, 2 inch and 4 inch',
			'tagline'       => 'Both reaches, one order.',
			'description'   => "The 2-inch and 4-inch handpieces together — so every operatory has the right geometry for the next case. The standard full outfit for a DEKA CO₂ practice.",
			'specs'         => [
				[ 'k' => 'Contents',   'v' => '2″ + 4″ handpieces' ],
				[ 'k' => 'Compatible', 'v' => 'DEKA CO₂ systems' ],
			],
			'featured'      => false,
		],
		[
			'slug'          => 'handpiece-package-upgrade-2-and-4-in-office',
			'name'          => 'Handpiece Package Upgrade · In-Office',
			'subtitle'      => 'Upgrade + dispatch service',
			'category'      => 'Service',
			'category_slug' => 'service',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$5,995.00',
			'price_note'    => 'Includes in-office service visit',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-Handpiece_Both_500x500-300x300.jpg',
			'image_alt'     => 'DEKA in-office handpiece upgrade',
			'tagline'       => 'Upgrade without the downtime.',
			'description'   => "Our clinical specialist visits the practice, retires the previous handpieces, installs the 2″ and 4″ upgrade package, and re-certifies the system. You return to the chair without interrupting the schedule.",
			'specs'         => [
				[ 'k' => 'Service',  'v' => 'In-office upgrade' ],
				[ 'k' => 'Contents', 'v' => '2″ + 4″ handpiece set' ],
			],
			'featured'      => false,
		],
		[
			'slug'          => 'co2-tube-replacement-in-office',
			'name'          => 'CO₂ Tube Replacement · In-Office',
			'subtitle'      => 'Service',
			'category'      => 'Service',
			'category_slug' => 'service',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$8,500.00',
			'price_note'    => 'Scheduled in-office visit',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/Deka-Dental-Lasers-copy-300x300.gif',
			'image_alt'     => 'DEKA CO₂ tube replacement service',
			'tagline'       => 'Fresh resonator, in a single visit.',
			'description'   => "When a CO₂ tube reaches end-of-life, our specialist replaces it on-site — recalibrating beam profile, power curve, and pulse integrity before handing the system back. The practice loses a morning, not a week.",
			'specs'         => [
				[ 'k' => 'Service',  'v' => 'CO₂ tube replacement' ],
				[ 'k' => 'Location', 'v' => 'In-office' ],
			],
			'featured'      => false,
		],
		[
			'slug'          => 'handpiece-package-upgrade-with-co2-tube-replacement-in-office',
			'name'          => 'Handpiece Upgrade + CO₂ Tube · In-Office',
			'subtitle'      => 'Full refresh service',
			'category'      => 'Service',
			'category_slug' => 'service',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$10,950.00',
			'price_note'    => 'Saves $1,545 vs. separate bookings',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/Deka-Dental-Lasers-copy-300x300.gif',
			'image_alt'     => 'DEKA full refresh service',
			'tagline'       => 'A decade-old system, new again.',
			'description'   => "The combined refresh: new CO₂ tube, new 2″ and 4″ handpiece set, full recalibration — all in one in-office visit. Designed for long-term DEKA practices whose US-20D or SmartXide is overdue for a second life.",
			'specs'         => [
				[ 'k' => 'Service',  'v' => 'Tube + handpiece refresh' ],
				[ 'k' => 'Location', 'v' => 'In-office' ],
			],
			'featured'      => false,
		],

		/* ─── 4. Attachments ───────────────────────────────────── */
		[
			'slug'          => '4-mirror-attachment',
			'name'          => '4″ Mirror Attachment',
			'subtitle'      => 'CO₂ attachment',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$325.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-4in_mirror_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 4 inch mirror attachment',
			'tagline'       => 'Angled access, reflected precisely.',
			'description'   => "The 4-inch mirror attachment for posterior access. Redirects the beam 90° through a gold-surfaced mirror calibrated to the system's wavelength.",
			'specs'         => [ [ 'k' => 'Length', 'v' => '4″' ], [ 'k' => 'Type', 'v' => 'Mirror · gold-surfaced' ] ],
			'featured'      => false,
		],
		[
			'slug'          => '4-straight-attachment',
			'name'          => '4″ Straight Attachment',
			'subtitle'      => 'CO₂ attachment',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$225.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-4in_straight_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 4 inch straight attachment',
			'tagline'       => 'The straightforward reach.',
			'description'   => "The straight 4-inch attachment for direct-line soft-tissue work. The default geometry for most incisions and vestibuloplasties.",
			'specs'         => [ [ 'k' => 'Length', 'v' => '4″' ], [ 'k' => 'Type', 'v' => 'Straight' ] ],
			'featured'      => false,
		],
		[
			'slug'          => '4-contra-angle-attachment',
			'name'          => '4″ Contra-Angle Attachment',
			'subtitle'      => 'Perio · CO₂ attachment',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$495.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA_Perio-Attachment_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 4 inch contra-angle perio attachment',
			'tagline'       => 'Into the pocket, around the corner.',
			'description'   => "The contra-angle attachment for perio access. Redirects the CO₂ beam for intra-sulcular work at the gumline — quiet, minimally-traumatic, and sparing of adjacent tissue.",
			'specs'         => [ [ 'k' => 'Length', 'v' => '4″' ], [ 'k' => 'Type', 'v' => 'Contra-angle · perio' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'mirror-spring-and-screw-for-4-contra-angle-attachment',
			'name'          => 'Mirror Spring & Screw · 4″ Contra-Angle',
			'subtitle'      => 'Replacement part',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$195.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/mirror_spring_screw_500x500-300x300.jpg',
			'image_alt'     => 'Mirror spring and screw replacement',
			'tagline'       => 'The small parts that matter.',
			'description'   => "Replacement mirror spring and retaining screw for the 4″ contra-angle attachment. Sized and tensioned to factory specification.",
			'specs'         => [ [ 'k' => 'Fits', 'v' => '4″ contra-angle attachment' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'mirror-for-4-contra-angle-attachment',
			'name'          => 'Mirror · 4″ Contra-Angle',
			'subtitle'      => 'Replacement gold mirror',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$125.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/Gold_Mirror_500x500-300x300.jpg',
			'image_alt'     => 'DEKA replacement gold mirror',
			'tagline'       => 'A clean reflection, re-stocked.',
			'description'   => "Replacement gold-surfaced mirror for the 4″ contra-angle attachment. Tuned to the CO₂ wavelength for maximum reflective efficiency.",
			'specs'         => [ [ 'k' => 'Surface', 'v' => 'Gold-coated' ], [ 'k' => 'Fits', 'v' => '4″ contra-angle' ] ],
			'featured'      => false,
		],
		[
			'slug'          => '2-mirror-attachment',
			'name'          => '2″ Mirror Attachment',
			'subtitle'      => 'CO₂ attachment',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$325.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-2in_mirror_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 2 inch mirror attachment',
			'tagline'       => 'Short reach, angled precisely.',
			'description'   => "The 2-inch mirror attachment for close, angled work. Pairs with the surgical handpiece for anterior redirection.",
			'specs'         => [ [ 'k' => 'Length', 'v' => '2″' ], [ 'k' => 'Type', 'v' => 'Mirror' ] ],
			'featured'      => false,
		],
		[
			'slug'          => '2-straight-attachment',
			'name'          => '2″ Straight Attachment',
			'subtitle'      => 'CO₂ attachment',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$295.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-2in_straight_ng_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 2 inch straight attachment',
			'tagline'       => 'Direct line, close quarters.',
			'description'   => "The 2-inch straight attachment for anterior direct-line work. Paired with the surgical handpiece for the tightest access in the operatory.",
			'specs'         => [ [ 'k' => 'Length', 'v' => '2″' ], [ 'k' => 'Type', 'v' => 'Straight' ] ],
			'featured'      => false,
		],
		[
			'slug'          => '2-straight-guided-attachment',
			'name'          => '2″ Straight Guided Attachment',
			'subtitle'      => 'CO₂ attachment · guided',
			'category'      => 'Attachment',
			'category_slug' => 'attachment',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$295.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-2in_straight_500x500-300x300.jpg',
			'image_alt'     => 'DEKA 2 inch straight guided attachment',
			'tagline'       => 'A steady line, every time.',
			'description'   => "The guided version of the 2-inch straight attachment — a visual sighting channel that helps the clinician maintain the cleanest possible approach vector, especially in tongue-tie releases.",
			'specs'         => [ [ 'k' => 'Length', 'v' => '2″' ], [ 'k' => 'Type', 'v' => 'Straight · guided' ] ],
			'featured'      => false,
		],

		/* ─── 5. Tips ─────────────────────────────────────────── */
		[
			'slug'          => 'threaded-tapered-perio-tip-10ct',
			'name'          => 'Threaded Tapered Perio Tip · 10 ct',
			'subtitle'      => 'CO₂ tip · 10-pack',
			'category'      => 'Tip',
			'category_slug' => 'tip',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$110.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-tip_tapered_500x500-300x300.jpg',
			'image_alt'     => 'DEKA threaded tapered perio tip 10 pack',
			'tagline'       => 'Ten deliveries, perfectly tapered.',
			'description'   => "A ten-pack of tapered perio tips for the CO₂ handpiece. The taper concentrates energy at the depth of the pocket while sparing the cuff above.",
			'specs'         => [ [ 'k' => 'Pack', 'v' => '10' ], [ 'k' => 'Shape', 'v' => 'Tapered · threaded' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'threaded-straight-tip-10ct',
			'name'          => 'Threaded Straight Tip · 10 ct',
			'subtitle'      => 'CO₂ tip · 10-pack',
			'category'      => 'Tip',
			'category_slug' => 'tip',
			'compatibility' => [ 'us-20d', 'smartxide-ultraspeed2' ],
			'price'         => '$110.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/DEKA-Tip_Straight_500x500-300x300.jpg',
			'image_alt'     => 'DEKA threaded straight tip 10 pack',
			'tagline'       => 'A month of incisions, in a pack.',
			'description'   => "A ten-pack of straight threaded tips for the CO₂ handpiece. The everyday workhorse for soft-tissue incisions and vestibuloplasties.",
			'specs'         => [ [ 'k' => 'Pack', 'v' => '10' ], [ 'k' => 'Shape', 'v' => 'Straight · threaded' ] ],
			'featured'      => false,
		],

		/* ─── 6. Marketing materials ────────────────────────────── */
		[
			'slug'          => 'quietnite-banner-stand',
			'name'          => 'QuietNite Laser Therapy Banner Stand',
			'subtitle'      => 'Reception banner',
			'category'      => 'Marketing',
			'category_slug' => 'marketing',
			'compatibility' => [],
			'price'         => '$695.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/bs-quiet-thm-300x300.jpg',
			'image_alt'     => 'QuietNite banner stand',
			'tagline'       => 'The conversation starts in the waiting room.',
			'description'   => "A full-height reception banner introducing QuietNite snoring-and-sleep laser therapy to patients before they reach the chair. Print-ready, drop-in, ready the day it arrives.",
			'specs'         => [ [ 'k' => 'Type', 'v' => 'Retractable banner stand' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'facial-aesthetics-banner-stand',
			'name'          => 'Facial Aesthetics Banner Stand',
			'subtitle'      => 'Reception banner',
			'category'      => 'Marketing',
			'category_slug' => 'marketing',
			'compatibility' => [],
			'price'         => '$695.00',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/bs-facial-thm-300x300.jpg',
			'image_alt'     => 'Facial aesthetics banner stand',
			'tagline'       => 'The aesthetics service, on the way in.',
			'description'   => "A full-height reception banner introducing the practice's facial aesthetics offering. Photography and copy tuned for the clinical-luxury positioning.",
			'specs'         => [ [ 'k' => 'Type', 'v' => 'Retractable banner stand' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-quietnite',
			'name'          => 'QuietNite Tri-Fold Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-quietnite-thm-300x300.jpg',
			'image_alt'     => 'QuietNite tri-fold brochure',
			'tagline'       => 'The take-home for the snoring conversation.',
			'description'   => "Tri-fold patient brochure explaining the QuietNite snoring and sleep laser protocol. Written for the chair-side consultation hand-off.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-periodontal',
			'name'          => 'Periodontal Laser Therapy Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-perio-thm-300x300.jpg',
			'image_alt'     => 'Periodontal laser therapy tri-fold brochure',
			'tagline'       => 'The perio conversation, written down.',
			'description'   => "Tri-fold brochure walking the patient through laser-assisted periodontal therapy — what it replaces, how it feels, and what the healing window looks like.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-facial-aesthetics',
			'name'          => 'Facial Aesthetics Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-facial-thm-300x300.jpg',
			'image_alt'     => 'Facial aesthetics tri-fold brochure',
			'tagline'       => 'The aesthetics service, told on paper.',
			'description'   => "Tri-fold brochure introducing dental-led facial aesthetics services — scope, protocol, and clinical positioning against non-dental providers.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-general',
			'name'          => 'General Laser Therapy Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-general-thm-300x300.jpg',
			'image_alt'     => 'General laser therapy tri-fold brochure',
			'tagline'       => 'The why, for every patient.',
			'description'   => "A general-purpose tri-fold that introduces laser dentistry to a new patient — indications, benefits, and what to expect chairside.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-pediatric',
			'name'          => 'Pediatric Laser Therapy Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-pediatric-thm-300x300.jpg',
			'image_alt'     => 'Pediatric laser therapy tri-fold brochure',
			'tagline'       => 'For the youngest patients.',
			'description'   => "Pediatric-focused tri-fold brochure, written for parents. Covers laser-assisted pediatric indications — from eruption issues to tongue-tie — in language parents accept.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-infant-lip-tongue-tie',
			'name'          => 'Infant Lip & Tongue Tie Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-infant-lip-thm-300x300.jpg',
			'image_alt'     => 'Infant lip and tongue tie tri-fold brochure',
			'tagline'       => 'The feeding conversation, clearly.',
			'description'   => "Tri-fold brochure for infant lip and tongue-tie revision — written for lactation consultants, pediatricians, and the parents they refer.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],
		[
			'slug'          => 'brochure-child-adult-lip-tie',
			'name'          => 'Child & Adult Lip Tie Brochure',
			'subtitle'      => 'Patient brochure',
			'category'      => 'Brochure',
			'category_slug' => 'brochure',
			'compatibility' => [],
			'price'         => '$195.00',
			'price_note'    => 'Per case',
			'image'         => 'https://dekadentallasers.com/wp-content/uploads/tf-child-adult-thm-300x300.jpg',
			'image_alt'     => 'Child and adult lip tie tri-fold brochure',
			'tagline'       => 'Later-life revision, explained.',
			'description'   => "Tri-fold brochure for lip-tie revision in older children and adults. Covers orthodontic, speech, and aesthetic indications at a reading level built for the chair.",
			'specs'         => [ [ 'k' => 'Format', 'v' => 'Tri-fold' ] ],
			'featured'      => false,
		],

	],

];
